# Generated by Django 2.2.7 on 2021-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
                ('edited_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'bmc_emp',
            },
        ),
    ]
